import { FilesetResolver, HandLandmarker } from 'https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.14/+esm';
const video=document.querySelector('#camera'),ink=document.querySelector('#ink'),hud=document.querySelector('#hud'),ictx=ink.getContext('2d'),hctx=hud.getContext('2d'),status=document.querySelector('#status'),welcome=document.querySelector('#welcome'),widthInput=document.querySelector('#width'),gestureHint=document.querySelector('#gestureHint'),modeButtons=[...document.querySelectorAll('.mode-btn')];
let landmarker,running=false,mirror=true,lastVideoTime=-1,strokes=[],current=null,smooth=null,lastPoint=null;
let controlMode='free',tool='pointer',penDown=false,gestureCandidate=null,gestureSince=0,lastGestureSwitch=0,pinchCloseFrames=0,pinchHistory=[];
const HOLD_MS=330,COOLDOWN_MS=450,ERASER_RADIUS=32,PINCH_DOWN=.43,PINCH_RELEASE_START=.50,TAIL_ROLLBACK_MS=95;
function resize(){const dpr=Math.min(devicePixelRatio||1,2),r=ink.getBoundingClientRect();for(const c of[ink,hud]){c.width=Math.round(r.width*dpr);c.height=Math.round(r.height*dpr);c.getContext('2d').setTransform(dpr,0,0,dpr,0,0)}redraw()}addEventListener('resize',resize);
async function initAI(){status.textContent='Carico hand tracking…';const vision=await FilesetResolver.forVisionTasks('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.14/wasm');landmarker=await HandLandmarker.createFromOptions(vision,{baseOptions:{modelAssetPath:'https://storage.googleapis.com/mediapipe-models/hand_landmarker/hand_landmarker/float16/1/hand_landmarker.task',delegate:'GPU'},runningMode:'VIDEO',numHands:1,minHandDetectionConfidence:.55,minHandPresenceConfidence:.5,minTrackingConfidence:.5})}
async function start(){try{await initAI();const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:1280},height:{ideal:720}},audio:false});video.srcObject=stream;await video.play();running=true;welcome.hidden=true;resize();refreshUI();requestAnimationFrame(loop)}catch(e){console.error(e);status.textContent='Errore fotocamera / permessi';alert('Impossibile avviare AirBoard. Aprilo via HTTPS e consenti la fotocamera.\n\n'+e.message)}}
document.querySelector('#start').onclick=start;document.querySelector('#clear').onclick=()=>{strokes=[];current=null;lastPoint=null;redraw()};document.querySelector('#undo').onclick=()=>{if(current){current=null;lastPoint=null}else strokes.pop();redraw()};document.querySelector('#mirror').onclick=()=>{mirror=!mirror;video.style.transform=mirror?'scaleX(-1)':'none'};document.querySelector('#download').onclick=savePNG;modeButtons.forEach(b=>b.onclick=()=>selectControl(b.dataset.mode));
function distance(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}function mapPoint(p){return{x:(mirror?1-p.x:p.x)*ink.clientWidth,y:p.y*ink.clientHeight}}function ema(p){if(!smooth)smooth=p;const a=.38;smooth={x:smooth.x+(p.x-smooth.x)*a,y:smooth.y+(p.y-smooth.y)*a};return smooth}
function drawStroke(ctx,s){if(!s?.points?.length)return;ctx.save();ctx.strokeStyle=s.color||'#dff7ff';ctx.lineWidth=s.width||6;ctx.lineCap='round';ctx.lineJoin='round';ctx.shadowColor='#71d7ff';ctx.shadowBlur=8;ctx.beginPath();const p=s.points;ctx.moveTo(p[0].x,p[0].y);for(let i=1;i<p.length;i++){const m={x:(p[i-1].x+p[i].x)/2,y:(p[i-1].y+p[i].y)/2};ctx.quadraticCurveTo(p[i-1].x,p[i-1].y,m.x,m.y)}ctx.stroke();ctx.restore()}function redraw(){ictx.clearRect(0,0,ink.clientWidth,ink.clientHeight);for(const s of strokes)drawStroke(ictx,s);if(current)drawStroke(ictx,current)}function commitStroke(){if(current?.points.length>1)strokes.push(current);current=null;lastPoint=null;redraw()}
function selectControl(m){commitStroke();penDown=false;pinchHistory=[];gestureCandidate=null;if(m==='free'){controlMode='free';tool='pointer'}else{controlMode='fixed';tool=m}refreshUI()}
function setGestureTool(t){if(controlMode!=='free'||t===tool)return;commitStroke();penDown=false;pinchHistory=[];tool=t;lastGestureSwitch=performance.now();gestureCandidate=null;refreshUI(true)}
function refreshUI(fromGesture=false){modeButtons.forEach(b=>b.classList.toggle('active',controlMode==='free'?b.dataset.mode==='free':b.dataset.mode===tool));if(controlMode==='free'){status.textContent=`✨ Libera · ${tool==='pointer'?'☝️ Punta':tool==='pen'?(penDown?'✏️ Writing':'✏️ Penna'):'◯ Gomma'}`;if(!gestureCandidate)gestureHint.textContent=fromGesture?'Gesto riconosciuto · gesti ancora attivi':'✨ Gesti attivi: ☝️ punta · 🤏 penna · ✋ gomma'}else{status.textContent=`🔒 ${tool==='pointer'?'☝️ Puntatore':tool==='pen'?(penDown?'✏️ Penna · WRITING':'✏️ Penna · READY'):'◯ Gomma'}`;gestureHint.textContent=tool==='pen'?(penDown?'Apri le dita = stop immediato':'🤏 Unisci pollice + indice per scrivere'):'🔒 Modalità fissa · riconoscimento gesti disattivato'}}
function fingerUp(lm,tip,pip){return lm[tip].y<lm[pip].y-.018}function pinchRatio(lm){return distance(lm[8],lm[4])/Math.max(distance(lm[0],lm[9]),.04)}
function classifyGesture(lm){const r=pinchRatio(lm),idx=fingerUp(lm,8,6),mid=fingerUp(lm,12,10),ring=fingerUp(lm,16,14),pinky=fingerUp(lm,20,18);const extended=[idx,mid,ring,pinky].filter(Boolean).length;if(r<PINCH_DOWN)return'pen';if(extended>=3)return'eraser';if(idx&&extended<=2)return'pointer';return null}
function handleFreeGesture(g,now){if(controlMode!=='free'||!g||g===tool||now-lastGestureSwitch<COOLDOWN_MS){gestureCandidate=null;return}if(g!==gestureCandidate){gestureCandidate=g;gestureSince=now;return}const progress=Math.min(1,(now-gestureSince)/HOLD_MS);gestureHint.textContent=`${g==='pointer'?'☝️ Punta':g==='pen'?'🤏 Penna':'✋ Gomma'} ${Math.round(progress*100)}%`;if(progress>=1)setGestureTool(g)}
function trimReleaseTail(releaseStart){if(!current?.points?.length)return;const cutoff=releaseStart-TAIL_ROLLBACK_MS;while(current.points.length>2&&current.points[current.points.length-1].t>=cutoff)current.points.pop();redraw()}
function updatePenContact(lm,now){const ratio=pinchRatio(lm);pinchHistory.push({t:now,r:ratio});while(pinchHistory.length&&now-pinchHistory[0].t>180)pinchHistory.shift();if(!penDown){if(ratio<PINCH_DOWN)pinchCloseFrames++;else pinchCloseFrames=0;if(pinchCloseFrames>=2){penDown=true;pinchCloseFrames=0;current={points:[],width:+widthInput.value,color:'#eafcff'};lastPoint=null;refreshUI()}}else{const prev=pinchHistory.length>1?pinchHistory[pinchHistory.length-2].r:ratio;const opening=ratio>prev+.012;const crossed=ratio>=PINCH_RELEASE_START;if(opening&&crossed){const firstOpening=[...pinchHistory].reverse().find((v,i,a)=>i===a.length-1||v.r<=a[i+1].r+.004);const releaseStart=firstOpening?.t||now;trimReleaseTail(releaseStart);penDown=false;pinchCloseFrames=0;commitStroke();refreshUI()}}}
function eraseAt(p){let changed=false;strokes=strokes.map(s=>{const chunks=[];let chunk=[];for(const q of s.points){if(Math.hypot(q.x-p.x,q.y-p.y)<=ERASER_RADIUS){if(chunk.length>1)chunks.push({...s,points:chunk});chunk=[];changed=true}else chunk.push(q)}if(chunk.length>1)chunks.push({...s,points:chunk});return chunks}).flat();if(changed)redraw()}
function updateHand(lm){const p=ema(mapPoint(lm[8])),now=performance.now();if(controlMode==='free')handleFreeGesture(classifyGesture(lm),now);if(tool==='pen'){updatePenContact(lm,now);if(penDown&&current&&(!lastPoint||Math.hypot(p.x-lastPoint.x,p.y-lastPoint.y)>1.3)){current.points.push({...p,t:now});lastPoint={...p};redraw()}}else{if(penDown){penDown=false;commitStroke()}if(tool==='eraser')eraseAt(p)}drawHUD(p);if(!gestureCandidate)refreshUI()}
function drawHUD(p){hctx.clearRect(0,0,hud.clientWidth,hud.clientHeight);hctx.save();hctx.beginPath();const radius=tool==='eraser'?ERASER_RADIUS:tool==='pen'?(penDown?10:8):7;hctx.arc(p.x,p.y,radius,0,Math.PI*2);if(tool==='eraser'||(tool==='pen'&&!penDown)){hctx.fillStyle='#ffffff18';hctx.strokeStyle='#fff';hctx.lineWidth=2;hctx.fill();hctx.stroke()}else{hctx.fillStyle=tool==='pen'?'#fff':'#7ee8ff';hctx.shadowColor='#70dfff';hctx.shadowBlur=16;hctx.fill()}hctx.restore()}
function noHand(){hctx.clearRect(0,0,hud.clientWidth,hud.clientHeight);smooth=null;if(penDown){penDown=false;commitStroke()}gestureCandidate=null;status.textContent='Mostra la mano'}async function loop(){if(!running)return;if(video.readyState>=2&&video.currentTime!==lastVideoTime){lastVideoTime=video.currentTime;const res=landmarker.detectForVideo(video,performance.now());res.landmarks?.length?updateHand(res.landmarks[0]):noHand()}requestAnimationFrame(loop)}function savePNG(){const out=document.createElement('canvas');out.width=ink.width;out.height=ink.height;out.getContext('2d').drawImage(ink,0,0);const a=document.createElement('a');a.download='airboard.png';a.href=out.toDataURL('image/png');a.click()}if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
